[package]
name = "folder-find"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.3.0"
humantime = "2.1.0"
rayon = "1.7.0"
size = "0.4.1"
